---
- name: Web server deploy
  hosts: web
  become: yes
  roles:
    - webserver

- name: Odoo server deploy
  hosts: odoo
  become: yes
  roles:
    - odoo

- name: Odoo on web server also
  hosts: web
  become: yes
  roles:
    - odoo
